### ISSUE TITLE
Not working (OS X - Chrome, Firefox, Safari)

### ISSUE THREAD

**Issue by nnx0r** [silviomoreto/scrollYou#5]
I did not try it in personal projects (yet), but just checked your temporary demo.
It does not seem to work / co-operate in your Bootstrap-Select plugin...

Browser versions tested on OS X Yosemite 10.10.3
Chrome - 42.0.2311.135 (64-bit)
Firefox - 37.0.2
Safari - 8.0.5 (10600.5.17)

Not sure what may cause the problem or wether it's compatible for OS X?

EDIT:
I see that it's been 2 years since latest release. Well I assume you have discontinued development of this plugin?

**Comment by silviomoreto** [comment]
Thanks for the Issue, but I am not working anymore in this project. If you want contribute and fix the issue I can add you as a contributor and you can made a PR to fix this.
